# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projet.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PIL import Image, ImageFilter
from matplotlib import pyplot as plt
import cv2

class Ui_Form:
    def __init__(self):


        self.filepath=None
        self.bw_filepath=None
        self.ct_filepath= None
    def import_image(self):
        filepath, _ = QFileDialog.getOpenFileName(None, 'Open file', '.', 'Images (*.png *.xpm *.jpg *.jpeg)')



        pixmap = QtGui.QPixmap(filepath)
        self.before.setPixmap(pixmap)
        self.filepath = filepath



    def black_and_white(self):

        # Open the image

        path_parts = self.filepath.split('/')

        filename = path_parts[-1]

        with Image.open(self.filepath) as img:
            # Convert the image to black and white
            bw_img = img.convert('L')

            # Save the black and white image

            bw_img_path = '/'.join(path_parts[:-1]) + '/bw_' + filename

            # print('/'.join(path_parts[:-1]) + '/bw_' + filename)

            bw_img.save(bw_img_path)
            # Return the black and white image as a PIL Image object

        pixmap = QtGui.QPixmap(bw_img_path)
        self.after.setPixmap(pixmap)

        self.bw_filepath = bw_img_path


    def contour(self):

        # Open the image

        path_parts = self.filepath.split('/')

        filename = path_parts[-1]
        if self.bw_filepath==None:
         with Image.open(self.filepath) as img:
            # Convert the image to black and white
            ct_img = img.filter(ImageFilter.CONTOUR)

            # Save the black and white image

            ct_img_path = '/'.join(path_parts[:-1]) + '/ct_' + filename

            # print('/'.join(path_parts[:-1]) + '/bw_' + filename)

            ct_img.save(ct_img_path)
            # Return the black and white image as a PIL Image object
        else :
            with Image.open(self.bw_filepath) as img:
                # Convert the image to black and white
                ct_img = img.filter(ImageFilter.CONTOUR)

                # Save the black and white image

                ct_img_path = '/'.join(path_parts[:-1]) + '/ct_' + filename

                # print('/'.join(path_parts[:-1]) + '/bw_' + filename)

                ct_img.save(ct_img_path)
                # Return the black and white image as a PIL Image object
        pixmap = QtGui.QPixmap(ct_img_path)
        self.after.setPixmap(pixmap)

        self.ct_filepath = ct_img_path

    def his(self, x):
        # Load the image
        img = cv2.imread(x)

        # Split the image into RGB channels
        b, g, r = cv2.split(img)

        # Set the histogram parameters
        histSize = 256  # Number of bins
        histRange = (0, 256)  # Range of values
        accumulate = False

        # Compute the histograms
        b_hist = cv2.calcHist([b], [0], None, [histSize], histRange, accumulate=accumulate)
        g_hist = cv2.calcHist([g], [0], None, [histSize], histRange, accumulate=accumulate)
        r_hist = cv2.calcHist([r], [0], None, [histSize], histRange, accumulate=accumulate)

        # Plot the histograms
        plt.figure(figsize=(8, 6))
        plt.title('RGB Histogram')
        plt.plot(b_hist, color='b', alpha=0.5)
        plt.plot(g_hist, color='g', alpha=0.5)
        plt.plot(r_hist, color='r', alpha=0.5)
        plt.xlim([0, histSize])
        plt.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1125, 855)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(Form)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(40, 40, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnc = QtWidgets.QPushButton(Form,clicked=lambda : self.his(self.filepath))
        self.btnc.setGeometry(QtCore.QRect(480, 620, 151, 101))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnc.setFont(font)
        self.btnc.setObjectName("btnc")

        self.btnd = QtWidgets.QPushButton(Form, clicked=self.black_and_white)

        self.btnd.setGeometry(QtCore.QRect(480, 470, 151, 91))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnd.setFont(font)
        self.btnd.setObjectName("btnd")
        self.btne = QtWidgets.QPushButton(Form, clicked=self.contour)
        self.btne.setGeometry(QtCore.QRect(480, 310, 151, 91))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btne.setFont(font)
        self.btne.setObjectName("btne")
        self.btnb = QtWidgets.QPushButton(Form, clicked=self.import_image)
        self.btnb.setGeometry(QtCore.QRect(490, 50, 111, 71))
        self.btnb.setObjectName("btnb")
        self.before = QtWidgets.QLabel(Form)
        self.before.setGeometry(QtCore.QRect(70, 310, 391, 401))
        self.before.setObjectName("before")
        self.after = QtWidgets.QLabel(Form)
        self.after.setGeometry(QtCore.QRect(650, 310, 451, 411))
        self.after.setObjectName("after")
        self.label_ = QtWidgets.QLabel(Form)
        self.label_.setGeometry(QtCore.QRect(870, -10, 231, 101))
        self.label_.setObjectName("label_")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "projet :traitement d\'image"))
        self.label.setText(_translate("Form", "importer une image :"))
        self.btnc.setText(_translate("Form", "histogramme"))
        self.btnd.setText(_translate("Form", "noir et blanc"))
        self.btne.setText(_translate("Form", "contour"))
        self.btnb.setText(_translate("Form", "browse images"))
        self.before.setText(_translate("Form", ""))
        self.after.setText(_translate("Form", ""))
        self.label_.setText(_translate("Form", "projet chehine melki infotronique b"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
